project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from todo import views


app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('todos/', views.todos, name='todos'),
    path('todos/<int:pk>/', views.todos, name='todos_pk'),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.pk}: {self.text}'

todo/forms.py
from django.forms import ModelForm
from todo.models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ('text',)

todo/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from todo.models import Todo
from todo.forms import TodoForm


def index(request):
    return HttpResponseRedirect(reverse('todo:todos'))


@login_required
def todos(request, pk=None):
    todo_form = None

    if request.method == 'POST':
        todo_form = TodoForm(request.POST)
        if todo_form.is_valid():
            todo_form.instance.user = request.user
            todo_form.save()
            todo_form = None

    if request.method == 'DELETE':
        todo = get_object_or_404(Todo, pk=pk)
        if todo.user == request.user:
            todo.delete()
        else:
            raise PermissionDenied('This todo item does not belong to you!')

    if not todo_form:
        todo_form = TodoForm()

    todos = Todo.objects.filter(user=request.user)
    context = {'todos': todos, 'todo_form': todo_form}

    return render(request, 'todo/index.html', context)

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://unpkg.com/htmx.org@1.9.3" integrity="sha384-lVb3Rd/Ca0AxaoZg5sACe8FJKF0tnUgR2Kd7ehUOG5GCcROv5uBIZsOqovBAcWua" crossorigin="anonymous"></script>
    <title>Todo</title>
</head>
<body hx-boost="true">

    <h1>Todos</h1>
    <hr>
    <h3>
    Welcome {{user}},
    <a href="{% url 'logout' %}">Log out</a>
    </h3>
    <hr>
    <ul>
    {% for todo in todos %}
    <li>
        ({{ todo.pk }}): {{ todo.text }}
        <span
            data-hx-delete="{% url 'todo:todos_pk' todo.pk %}"
            data-hx-trigger="click"
            data-hx-target="body"
        >X</span>
    </li>
    {% endfor %}

    {% if not todos %}
    <h4>No todos at the moment...</h4>
    {% endif %}
    </ul>



    <form method="POST" action="{% url 'todo:todos' %}">
        {% csrf_token %}
        {{ todo_form }}
        <button>Submit</button>
    </form>

    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
            event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>
</body>
</html>